#This is the build configuration file for the Cloud Build
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-world-nginx', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/hello-world-nginx']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'app.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=${_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
